name: Remote update execution
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 194.28.84.49
        username: builder
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
                    ls -l ~
